### ISSUE TITLE
运行报错，没有一个成功的

### ISSUE THREAD

**Issue by yyf1029** [chineseocr/chineseocr#132]
运行程序后结果没有成功的，请问是什么原因造成的
Traceback (most recent call last):
  File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/app.py", line 58, in POST
    ifadjustDegree=False##是否先小角度调整文字倾斜角度
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/model.py", line 133, in model
    text_recs = text_detect(**config)
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/model.py", line 52, in text_detect
    MIN_NUM_PROPOSALS)
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/detectors.py", line 81, in detect
    text_lines=self.text_proposal_connector.get_text_lines(text_proposals, scores, size)##合并文本行
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_connector.py", line 29, in get_text_lines
    tp_groups=self.group_text_proposals(text_proposals, scores, im_size)##find the text line
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_connector.py", line 12, in group_text_proposals
    graph=self.graph_builder.build_graph(text_proposals, scores, im_size)
  File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_graph_builder.py", line 88, in build_graph
    boxes_table[int(box[0])].append(index)
TypeError: only size-1 arrays can be converted to Python scalars

127.0.0.1:52878 - - [03/Jan/2019 10:14:05] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

**Comment by 489397771** [comment]
> 运行程序后结果没有成功的，请问是什么原因造成的
> Traceback (most recent call last):
> File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 257, in process
> return self.handle()
> File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 248, in handle
> return self._delegate(fn, self.fvars, args)
> File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
> return handle_class(cls)
> File "/home/steven/anaconda3/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
> return tocall(*args)
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/app.py", line 58, in POST
> ifadjustDegree=False##是否先小角度调整文字倾斜角度
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/model.py", line 133, in model
> text_recs = text_detect(**config)
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/model.py", line 52, in text_detect
> MIN_NUM_PROPOSALS)
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/detectors.py", line 81, in detect
> text_lines=self.text_proposal_connector.get_text_lines(text_proposals, scores, size)##合并文本行
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_connector.py", line 29, in get_text_lines
> tp_groups=self.group_text_proposals(text_proposals, scores, im_size)##find the text line
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_connector.py", line 12, in group_text_proposals
> graph=self.graph_builder.build_graph(text_proposals, scores, im_size)
> File "/home/steven/pyworkshop/yolo3crnn/chineseocr/text/detector/text_proposal_graph_builder.py", line 88, in build_graph
> boxes_table[int(box[0])].append(index)
> TypeError: only size-1 arrays can be converted to Python scalars
> 
> 127.0.0.1:52878 - - [03/Jan/2019 10:14:05] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

我也出现了这个错误，请问你的这个问题解决了么？box[0]是个list，boxes_table[int(box[0])].append(index)这个代码是什么作用呢？
