### ISSUE TITLE
Corrupted image for 3090 Corrupted image for 3092......

### ISSUE THREAD

**Issue by Aurora11111** [chineseocr/chineseocr#15]
运行训练crnn_pytorch的时候一直报这个错,我的数据集是用synthdata-zh生成的 ,检查了一下,还是找不到是哪里与有问题,当我设置worker等于0报错如下:
...
Corrupted image for 21320
...
Traceback (most recent call last):
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 54, in __getitem__
    img = Image.open(dataBytesIO).convert('L')
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f22dda35468>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 54, in __getitem__
    img = Image.open(dataBytesIO).convert('L')
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f22dda35518>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 202, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 176, in trainBatch
    data = train_iter.next()
  File "/home/rice/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 259, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/rice/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 259, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 57, in __getitem__
    return self[index + 1]
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 57, in __getitem__
    return self[index + 1]
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 57, in __getitem__
    return self[index + 1]
  [Previous line repeated 324 more times]
  File "/home/rice/PycharmProjects/crnn.pytorch-master/dataset.py", line 54, in __getitem__
    img = Image.open(dataBytesIO).convert('L')
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/Image.py", line 2609, in open
    im = _open_core(fp, filename, prefix)
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/Image.py", line 2599, in _open_core
    im = factory(fp, filename)
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/ImageFile.py", line 102, in __init__
    self._open()
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/PIL/MpegImagePlugin.py", line 69, in _open
    s = BitStream(self.fp)
RecursionError: maximum recursion depth exceeded while calling a Python object

Process finished with exit code 1

当我设置worker大于0报错如下:
...
Corrupted image for 17529
...
Traceback (most recent call last):
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 202, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 176, in trainBatch
    data = train_iter.next()
  File "/home/rice/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/home/rice/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/rice/anaconda3/envs/tensorflow1/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/home/rice/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4409) exited unexpectedly with exit code 1.

Process finished with exit code 1

**Comment by wenlihaoyu** [comment]
“OSError: cannot identify image file <_io.BytesIO object at 0x7f22dda35518>” 应该是你生成的图像有问题哈
