### ISSUE TITLE
请教YOLO3训练报错

### ISSUE THREAD

**Issue by wxq7** [chineseocr/chineseocr#170]
感谢楼主开源的代码
想要训练文字检测部分，使用text-train.ipyth时发生一下错误：

Using TensorFlow backend.
2019-03-06 19:53:29.854429: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-06 19:53:29.974323: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-06 19:53:29.974720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
totalMemory: 10.73GiB freeMemory: 10.15GiB
2019-03-06 19:53:29.974731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-03-06 19:53:30.173397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-06 19:53:30.173416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-03-06 19:53:30.173421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-03-06 19:53:30.173558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9887 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2019-03-06 19:53:30.254607: I tensorflow/core/common_runtime/direct_session.cc:284] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5

total: 100
total: 100
Epoch 1/2
2019-03-06 19:53:42.232734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-03-06 19:53:42.232762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-06 19:53:42.232767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-03-06 19:53:42.232771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-03-06 19:53:42.232851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9887 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-03-06 19:53:55.000208: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=43264, n=32, k=64
	 [[Node: conv2d_2/Conv2D = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv2d_2/Conv2D_grad/Conv2DBackpropInput"], data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](leaky_re_lu_1/sub, conv2d_2/kernel/read)]]
	 [[Node: loss_1/wh_loss_loss/Mean_2/_2247 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_25531_loss_1/wh_loss_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wxq/wxq-home/Program/chineseocr-master/train/text/text-train.py", line 214, in <module>
    validation_steps=num_val
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1598, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_generator.py", line 191, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1390, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2824, in __call__
    fetches=fetches, feed_dict=feed_dict, **self.session_kwargs)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=43264, n=32, k=64
	 [[Node: conv2d_2/Conv2D = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv2d_2/Conv2D_grad/Conv2DBackpropInput"], data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](leaky_re_lu_1/sub, conv2d_2/kernel/read)]]
	 [[Node: loss_1/wh_loss_loss/Mean_2/_2247 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_25531_loss_1/wh_loss_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'conv2d_2/Conv2D', defined at:
  File "/home/wxq/wxq-home/Program/chineseocr-master/train/text/text-train.py", line 192, in <module>
    textModel = yolo_text(num_classes,anchors,train=True)
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 378, in yolo_text
    darknet = Model(imgInput, darknet_body(imgInput))
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 80, in darknet_body
    x = resblock_body(x, 64, 1)
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 73, in resblock_body
    DarknetConv2D_BN_Leaky(num_filters, (3,3)))(x)
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/wxq/wxq-home/Program/chineseocr-master/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 168, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 956, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/wxq/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

**InternalError (see above for traceback): Blas SGEMM launch failed : m=43264, n=32, k=64**
	 [[Node: conv2d_2/Conv2D = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv2d_2/Conv2D_grad/Conv2DBackpropInput"], data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](leaky_re_lu_1/sub, conv2d_2/kernel/read)]]
	 [[Node: loss_1/wh_loss_loss/Mean_2/_2247 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_25531_loss_1/wh_loss_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

经过查询有说是GPU显存不足，尝试了释放显存和限制tensorflow使用的显存大小后还是报出这个错误，求解
系统：ubuntu16.04
GPU：rtx2080ti
驱动：410.78
cuda：9.0
tensorflow-gpu==1.8.0

**Comment by zhoujungis** [comment]
请问你是怎么解决的啊？

**Comment by wxq7** [comment]
@zhoujungis 在我上一楼层说明的环境没有办法运行。
我又分别在1080ti， titan x显卡，使用384驱动程序，其余环境相同进行实验，都可以成功运行;
我感觉可能的原因是2080ti不兼容，或显卡驱动版本过高，与tensorflow-gou1.8部分不兼容

**Comment by xdwjc** [comment]
你好，我显卡是RTX2080，tensorflow是1.8 驱动是418，也遇到了这种问题，请问你解决了吗

**Comment by zhoujungis** [comment]
@xdwjc 我重装了cuda10.0，cudnn7.3.1，vs2017，然后在[github上](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.12.0/py36/GPU/cuda100cudnn73avx2)下载了tensorflow1.12的wheel安装的，显卡驱动在英伟达官网下的418，成功了

**Comment by xdwjc** [comment]
好的谢谢，请问你ubuntu装的是16还是18

**Comment by zhoujungis** [comment]
@xdwjc 我用的win10，尴尬了

**Comment by dzyink** [comment]
请问，代码运行到下面这里的时候，报错“IndexError: list index out of range”，怎么解决的？
`
textModel.compile(optimizer=adam,
                  loss={
                      'xy_loss': lambda y_true, y_pred: y_pred,
                      'wh_loss': lambda y_true, y_pred: y_pred,
                      'confidence_loss': lambda y_true, y_pred: y_pred,
                      'class_loss': lambda y_true, y_pred: y_pred,
                  })
`

**Comment by sihangsong** [comment]
> 请问，代码运行到下面这里的时候，报错“IndexError: list index out of range”，怎么解决的？
> 
> ```
> textModel.compile(optimizer=adam,
>                   loss={
>                       'xy_loss': lambda y_true, y_pred: y_pred,
>                       'wh_loss': lambda y_true, y_pred: y_pred,
>                       'confidence_loss': lambda y_true, y_pred: y_pred,
>                       'class_loss': lambda y_true, y_pred: y_pred,
>                   })
> ```

同问 @wenlihaoyu

**Comment by WangXuanBT** [comment]
> 请问，代码运行到下面这里的时候，报错“IndexError: list index out of range”，怎么解决的？
> 
> ```
> textModel.compile(optimizer=adam,
>                   loss={
>                       'xy_loss': lambda y_true, y_pred: y_pred,
>                       'wh_loss': lambda y_true, y_pred: y_pred,
>                       'confidence_loss': lambda y_true, y_pred: y_pred,
>                       'class_loss': lambda y_true, y_pred: y_pred,
>                   })
> ```

你好，请问问题解决了吗？我现在也遇到了这个问题。。。

**Comment by ChenShaomin** [comment]
> > 请问，代码运行到下面这里的时候，报错“IndexError: list index out of range”，怎么解决的？
> > ```
> > textModel.compile(optimizer=adam,
> >                   loss={
> >                       'xy_loss': lambda y_true, y_pred: y_pred,
> >                       'wh_loss': lambda y_true, y_pred: y_pred,
> >                       'confidence_loss': lambda y_true, y_pred: y_pred,
> >                       'class_loss': lambda y_true, y_pred: y_pred,
> >                   })
> > ```
> 
> 你好，请问问题解决了吗？我现在也遇到了这个问题。。。

主要是因为tensorflow版本高了，可以找到最终报错的那行代码，注释掉就可以训练了

**Comment by QiaoKes** [comment]
请问在2080ti的环境下运行的问题解决了吗

**Comment by 2042644107** [comment]
> @xdwjc 我重装了cuda10.0，cudnn7.3.1，vs2017，然后在[github上](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.12.0/py36/GPU/cuda100cudnn73avx2)下载了tensorflow1.12的wheel安装的，显卡驱动在英伟达官网下的418，成功了

您好，您用的418.几的驱动版本呀，还有cuda是10.0.130吗？谢谢回答

**Comment by 2042644107** [comment]
@zhoujungis  请问您驱动版本是418.几呀，还有cuda的版本是10.0.130吗，感谢回答

**Comment by zhoujungis** [comment]
> @zhoujungis 请问您驱动版本是418.几呀，还有cuda的版本是10.0.130吗，感谢回答

当时只有418和10.0

**Comment by 2042644107** [comment]
麻烦您帮我看一下您cmd里输入nvcc -V后出来的最后一行以及输入nvidia-smi输出的框的最上边的Driver Version: 后面的版本号，麻烦您了，谢谢

**Comment by 2042644107** [comment]
@zhoujungis 麻烦您帮我看一下您cmd里输入nvcc -V后出来的最后一行以及输入nvidia-smi输出的框的最上边的Driver Version: 后面的版本号，麻烦您了，谢谢

**Comment by zlszhonglongshen** [comment]
@wxq7  你好，能提供一下你的训练集以及训练代码吗？

**Comment by hong3731** [comment]
> > > 请问，代码运行到下面这里的时候，报错“IndexError: list index out of range”，怎么解决的？
> > > ```
> > > textModel.compile(optimizer=adam,
> > >                   loss={
> > >                       'xy_loss': lambda y_true, y_pred: y_pred,
> > >                       'wh_loss': lambda y_true, y_pred: y_pred,
> > >                       'confidence_loss': lambda y_true, y_pred: y_pred,
> > >                       'class_loss': lambda y_true, y_pred: y_pred,
> > >                   })
> > > ```
> > 
> > 
> > 你好，请问问题解决了吗？我现在也遇到了这个问题。。。
> 
> 主要是因为tensorflow版本高了，可以找到最终报错的那行代码，注释掉就可以训练了

你好，我也遇到了这个问题，能指导一下，祖居是注释掉那里的吗？
