### ISSUE TITLE
keep_inds=nms(np.hstack((text_proposals, scores)), TEXT_PROPOSALS_NMS_THRESH)

### ISSUE THREAD

**Issue by hufangjian** [chineseocr/chineseocr#18]
你好，CPU版本的测试没有问题，但是我用GPU版本的时候一直报这个错误，
Traceback (most recent call last):
  File "backend_demo.py", line 32, in <module>
    leftAdjust=True,rightAdjust=True,alph=0.1)
  File "/home/hufangjian/train_ticket/chineseocr/model.py", line 193, in model
    text_recs,tmp = text_detect(**config)
  File "/home/hufangjian/train_ticket/chineseocr/model.py", line 42, in text_detect
    MIN_NUM_PROPOSALS)
  File "/home/hufangjian/train_ticket/chineseocr/detector/detectors.py", line 65, in detect
    keep_inds=nms(np.hstack((text_proposals, scores)), TEXT_PROPOSALS_NMS_THRESH)##nms \u8fc7\u6ee4\u91cd\u590d\u7684box 
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/numpy/core/shape_base.py", line 291, in hstack
    return _nx.concatenate(arrs, 0)
ValueError: all the input arrays must have same number of dimensions

**Comment by hufangjian** [comment]
我查了一下，GPU版本没有检测出来文本。

**Comment by wenlihaoyu** [comment]
你在 keep_inds=nms(np.hstack((text_proposals, scores)), TEXT_PROPOSALS_NMS_THRESH)##nms  代码前,加一句:print(text_proposals.shape,scores.shape),看纬度是否一样

**Comment by hufangjian** [comment]
你好，我测试yolo检测文本
 ./darknet detector test ../chineseocr/models/text.data ../chineseocr/models/text.cfg ../chineseocr/models/text.weights 16.jpg -thresh 0.1 -nms_thesh 0.8
输出的prediction.png 是有文本标注的。
但是，
我在/detector/detectors.py  的59行加了print(text_proposals, scores) 是没有输出的 也就是没有检测出来文本，请问是TEXT_PROPOSALS_MIN_SCORE=0.7 设置 text的概率是吧？
