### ISSUE TITLE
运行ipython3 app.py 8080最后卡住

### ISSUE THREAD

**Issue by globalmaster** [chineseocr/chineseocr#185]
你好，我正确配置了GPU的环境，运行ipython3 app.py 8080最后卡住，输出信息如下：

Nms engine gpu_nms: <built-in function gpu_nms> ,cython_nms: None ,python_nms: <function nms at 0x7fb85f4eda60>
2019-03-17 15:52:39.285660: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-17 15:52:39.289852: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-17 15:52:39.290164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.873
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 6.68GiB
2019-03-17 15:52:39.290175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-17 15:52:39.460998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-17 15:52:39.461025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-17 15:52:39.461032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-17 15:52:39.461176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6437 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From /media/jack/code/clion_kdevelop/OCR/chineseocr/text/opencv_dnn_detect.py:14: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2019-03-17 15:52:44.247480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-17 15:52:44.247513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-17 15:52:44.247519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-17 15:52:44.247524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-17 15:52:44.247637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6437 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Text detect engine:keras
http://0.0.0.0:8080/

请问该如何解决？ @zergmk2 @wenlihaoyu @callinglove

**Comment by AlanNewImage** [comment]
浏览器输入：
http://0.0.0.0:8080/ocr

**Comment by globalmaster** [comment]
> 浏览器输入：
> http://0.0.0.0:8080/ocr

你好，我在浏览器输入http://0.0.0.0:8080/ocr，并加载图片之后，页面一直处于处理转圈的状态，并不能识别，输出如下信息，请问这是什么情况？谢谢！

127.0.0.1:47776 - - [18/Mar/2019 15:16:12] "HTTP/1.1 POST /ocr" - 500 Internal Server Error
127.0.0.1:47794 - - [18/Mar/2019 15:17:41] "HTTP/1.1 GET /ocr" - 200 OK
127.0.0.1:47794 - - [18/Mar/2019 15:17:41] "HTTP/1.1 GET /static/js/jquery.js" - 200 
127.0.0.1:47796 - - [18/Mar/2019 15:17:41] "HTTP/1.1 GET /static/js/jquery.form.js" - 200 
127.0.0.1:47796 - - [18/Mar/2019 15:17:42] "HTTP/1.1 GET /static/img/loading.gif" - 304 Not Modified
127.0.0.1:47796 - - [18/Mar/2019 15:17:42] "HTTP/1.1 GET /static/js/helps.js" - 304 Not Modified
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 257, in process
    return self.handle()
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/media/jack/code/clion_kdevelop/OCR/chineseocr/app.py", line 38, in POST
    data = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

127.0.0.1:47796 - - [18/Mar/2019 15:17:51] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

**Comment by AlanNewImage** [comment]
换个图

**Comment by globalmaster** [comment]
> 换个图

谢谢你，我运行test.ipynb成功了，在浏览器里加载图片没有成功

**Comment by wenlihaoyu** [comment]
@globalmaster 建议你用conda去配置环境。

**Comment by chky** [comment]
127.0.0.1:45478 - - [15/Oct/2019 22:00:29] "HTTP/1.1 POST /ocr" - 500 Internal Server Error
same as you

**Comment by chky** [comment]
The problem " InternalError (see above for traceback): Blas SGEMM launch failed : m=81920..." also occurred, I searched for solution and it says "it is become tensorflow occupys gpu resource, just reboot, then it will work". So I reboot my computer and it really works!

**Comment by a112a** [comment]
你好，请问进入网页后网页上的按钮部分不能动是什么原因呢
