### ISSUE TITLE
keras版本的ocr 访问 http://127.0.0.1:8088/ocr报错

### ISSUE THREAD

**Issue by QQ2737499951** [chineseocr/chineseocr#227]
博主您好，很激动看到您又更新了项目，我用了keras版本的ocr测试，报如下这个错误，请问这是什么原因呢：
<class 'UnicodeDecodeError'> at /ocr
'gbk' codec can't decode byte 0xab in position 428: illegal multibyte sequence
Python	d:\program files\python368\lib\site-packages\web\debugerror.py in _get_lines_from_file, line 245
Web	GET http://127.0.0.1:8088/ocr
这个貌似是编码的问题？

=================

Text detect engine:keras
http://0.0.0.0:8088/
Traceback (most recent call last):
  File "d:\program files\python368\lib\site-packages\web\application.py", line 257, in process
    return self.handle()
  File "d:\program files\python368\lib\site-packages\web\application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "d:\program files\python368\lib\site-packages\web\application.py", line 488, in _delegate
    return handle_class(cls)
  File "d:\program files\python368\lib\site-packages\web\application.py", line 466, in handle_class
    return tocall(*args)
  File "D:\Tensorflow\pytorch\chineseocr\app.py", line 35, in GET
    return render.ocr(post)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1034, in __getattr__
    t = self._template(name)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1031, in _template
    return self._load_template(name)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1016, in _load_template
    return Template(open(path).read(), filename=path, **self._keywords)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 1018: illegal multibyte sequence

Traceback (most recent call last):
  File "d:\program files\python368\lib\site-packages\web\application.py", line 257, in process
    return self.handle()
  File "d:\program files\python368\lib\site-packages\web\application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "d:\program files\python368\lib\site-packages\web\application.py", line 488, in _delegate
    return handle_class(cls)
  File "d:\program files\python368\lib\site-packages\web\application.py", line 466, in handle_class
    return tocall(*args)
  File "D:\Tensorflow\pytorch\chineseocr\app.py", line 35, in GET
    return render.ocr(post)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1034, in __getattr__
    t = self._template(name)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1031, in _template
    return self._load_template(name)
  File "d:\program files\python368\lib\site-packages\web\template.py", line 1016, in _load_template
    return Template(open(path).read(), filename=path, **self._keywords)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 1018: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python368\lib\site-packages\web\application.py", line 255, in process
    return p(lambda: process(processors))
  File "d:\program files\python368\lib\site-packages\web\application.py", line 643, in processor
    return handler()
  File "d:\program files\python368\lib\site-packages\web\application.py", line 255, in <lambda>
    return p(lambda: process(processors))
  File "d:\program files\python368\lib\site-packages\web\application.py", line 264, in process
    raise self.internalerror()
  File "d:\program files\python368\lib\site-packages\web\application.py", line 545, in internalerror
    return debugerror()
  File "d:\program files\python368\lib\site-packages\web\debugerror.py", line 313, in debugerror
    return web._InternalError(djangoerror())
  File "d:\program files\python368\lib\site-packages\web\debugerror.py", line 271, in djangoerror
    _get_lines_from_file(filename, lineno, 7)
  File "d:\program files\python368\lib\site-packages\web\debugerror.py", line 246, in _get_lines_from_file
    source = open(filename).readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 428: illegal multibyte sequence

127.0.0.1:5123 - - [24/Apr/2019 09:45:49] "HTTP/1.1 GET /ocr" - 500 Internal Server Error
127.0.0.1:5123 - - [24/Apr/2019 09:45:49] "HTTP/1.1 GET /favicon.ico" - 404 Not Found

**Comment by GavinWangxj** [comment]
我也遇到了，在linux环境是不存在这个问题的。在windows环境下会遇到读取文件（py和html）时报错。又不方便改这些模块的源码，不知道你解决没呢？

**Comment by QQ2737499951** [comment]
> 我也遇到了，在linux环境是不存在这个问题的。在windows环境下会遇到读取文件（py和html）时报错。又不方便改这些模块的源码，不知道你解决没呢？

你是cpu版还是GPU版的？安装成功了没？可以加QQ2737499951 沟通交流学习一下，谢谢

**Comment by GavinWangxj** [comment]
已加Q    centos的cpu版安装成功了。但是Windows的gpu版遇到问题了，windows下更适合调试。问题出在是windows下Python3使用open()函数打开文件时会默认使用gbk解码。而linux默认就是uft-8。我在想办法能不能改掉默认编码而不是每个open()函数上指定utf-8编码

**Comment by GavinWangxj** [comment]
已经解决了，还是根据提示去D:\ProgramData\Anaconda3\Lib\site-packages\web下将template.py和debugerror.py中所有涉及文件读取的的代码加上了encoding='utf-8'

**Comment by GavinWangxj** [comment]
已经解决了，没有找到一劳永逸的方案，还是根据提示去D:\ProgramData\Anaconda3\Lib\site-packages\web下将template.py和debugerror.py中所有涉及文件读取的的代码加上了encoding='utf-8'  你可以试试

**Comment by QQ2737499951** [comment]
> 已经解决了，没有找到一劳永逸的方案，还是根据提示去D:\ProgramData\Anaconda3\Lib\site-packages\web下将template.py和debugerror.py中所有涉及文件读取的的代码加上了encoding='utf-8' 你可以试试

=========
谢谢
解决Python在windows平台默认编码(encoding)为gbk所导致的open()函数报错及其他编码问题
注意 以下提到的Python均指的Python3.7
在windows平台下使用python内置函数 open() 时发现,当不传递encoding参数时，会自动采用gbk(cp936)编码打开文件，而当下很大部分文件的编码都是UTF-8。

我们当然可以通过每次手动传参encoding='utf-8'，但是略显冗余，而且有很多外国的第三方包，里面调用的内置open()函数并没有提供接口让我们指定encoding，这就会导致这些包在windows平台上使用时，常会出现如 "UnicodeDecodeError: 'gbk' codec can't decode byte 0x91 in position 209: illegal multibyte sequence" 的报错



可以发现当open不传递encoding参数时，是默认调用locale.getpreferredencoding()方法来获取当前平台的“默认编码类型”,继续查看相关文档，发现有两种方法可以指定windows平台下Python运行时的“默认编码类型”。

1. 指定sys.flags.utf8_mode(推荐)
通过运行脚本是添加命令行参数 -X utf8（注意是跟在python.exe后面的interpreter option,不是跟在要运行脚本后面的parameters!）

指定sys.flags.utf8_mode参数之后，Python运行时会在很多场景下自动使用utf-8编码，而不是win默认的gbk(cp936)编码。

2. 直接重写_locale(兼容老版本)
import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])
复制代码
python解释器会取_getdefaultlocale()[1]作为默认编码类型，重写后，会改变当前运行环境下的所有模块的默认编码。

总之，使用以上两种方法后，windows平台下，open()函数会默认用utf-8编码打开文件，其实不止open()方法，跨模块、全局改变python解释器的默认编码为utf-8,会带来很多使用上的便利，而不需要被gbk编码报错的噩梦所纠缠。

参考  [https://juejin.im/post/5bd2b6d5e51d45735c3c0453](https://juejin.im/post/5bd2b6d5e51d45735c3c0453)
