### ISSUE TITLE
 pushd text/detector/utils && sh make.sh && popd   cannot stat 'utils/*': No such file or directory

### ISSUE THREAD

**Issue by QQ2737499951** [chineseocr/chineseocr#229]
TengLong@tenglong-PC MINGW64 /D/Tensorflow/pytorch/chineseocr (master)
$ pushd text/detector/utils && sh make.sh && popd
/D/Tensorflow/pytorch/chineseocr/text/detector/utils /D/Tensorflow/pytorch/chineseocr
d:\program files\python368\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\Tensorflow\pytorch\chineseocr\text\detector\utils\cython_nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
d:\program files\python368\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\Tensorflow\pytorch\chineseocr\text\detector\utils\gpu_nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 36, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
OSError: The CUDA nvcc path could not be located in D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc
mv: cannot stat 'utils/*': No such file or directory
/D/Tensorflow/pytorch/chineseocr

**Comment by QQ2737499951** [comment]
34行   'lib64': pjoin(home, 'lib64')}    ，在 WIN +cuda10系统下改为： 'lib64': pjoin(home, 'lib', 'x64')}
因为lib目录在这里“lib\x64”， D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64

**Comment by QQ2737499951** [comment]
> 34行 'lib64': pjoin(home, 'lib64')} ，在 WIN +cuda10系统下改为： 'lib64': pjoin(home, 'lib', 'x64')}
> 因为lib目录在这里“lib\x64”， D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64
==============
D:\Tensorflow\pytorch\chineseocr\text\detector\utils>python setup_win.py build_ext --inplace
Traceback (most recent call last):
  File "setup_win.py", line 43, in <module>
    CUDA = locate_cuda()
  File "setup_win.py", line 39, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
OSError: The CUDA nvcc path could not be located in D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc

=========
原因是nvcc.exe路径错误，nvcc.exe在D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin
22行   原始是 nvcc = pjoin(home, 'bin', 'nvcc')   改为 nvcc = pjoin(home, 'bin') 

===========

运行后提示 

  File "setup_win.py", line 78, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup_win.py", line 53, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

**Comment by wenlihaoyu** [comment]
windows没有办法，目前没有机器用来测试，只有你们自己想办法了

**Comment by QQ2737499951** [comment]
> windows没有办法，目前没有机器用来测试，只有你们自己想办法了

## python版本nms无须执行下一步      
pushd text/detector/utils && sh make.sh && popd  
  请问一下，gpu的，python ，为什么不需要这步呢？

**Comment by QQ2737499951** [comment]
Nms engine gpu_nms: None ,cython_nms: None ,python_nms: <function nms at 0x00000162C9CE58C8>

原来python没有用 gpu_nms:和 cython_nms:
直接用的python_nms
