### ISSUE TITLE
使用keras_detect报错FailedPreconditionError

### ISSUE THREAD

**Issue by onmywei** [chineseocr/chineseocr#285]
Traceback (most recent call last):
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value batch_normalization_21/beta
	 [[Node: batch_normalization_21/beta/read = Identity[T=DT_FLOAT, _class=["loc:@batch_normalization_21/cond/FusedBatchNorm_1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](batch_normalization_21/beta)]]
	 [[Node: strided_slice_53/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3459_strided_slice_53", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ypl/GitProjects/chineseocr/text/keras_detect.py", line 82, in <module>
    a = text_detect(img)
  File "/home/ypl/GitProjects/chineseocr/text/keras_detect.py", line 63, in text_detect
    K.learning_phase(): 0
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value batch_normalization_21/beta
	 [[Node: batch_normalization_21/beta/read = Identity[T=DT_FLOAT, _class=["loc:@batch_normalization_21/cond/FusedBatchNorm_1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](batch_normalization_21/beta)]]
	 [[Node: strided_slice_53/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3459_strided_slice_53", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'batch_normalization_21/beta/read', defined at:
  File "/home/ypl/GitProjects/chineseocr/text/keras_detect.py", line 20, in <module>
    textModel = yolo_text(num_classes,anchors)
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 378, in yolo_text
    darknet = Model(imgInput, darknet_body(imgInput))
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 82, in darknet_body
    x = resblock_body(x, 256, 8)
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 73, in resblock_body
    DarknetConv2D_BN_Leaky(num_filters, (3,3)))(x)
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/ypl/GitProjects/chineseocr/text/keras_yolo3.py", line 43, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 699, in __call__
    self.build(input_shapes)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 299, in build
    trainable=True)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 546, in add_variable
    partitioner=partitioner)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/training/checkpointable.py", line 436, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 786, in _get_single_variable
    use_resource=use_resource)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2220, in variable
    use_resource=use_resource)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2210, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2193, in default_variable_creator
    constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 397, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3187, in identity
    "Identity", input=input, name=name)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ypl/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value batch_normalization_21/beta
	 [[Node: batch_normalization_21/beta/read = Identity[T=DT_FLOAT, _class=["loc:@batch_normalization_21/cond/FusedBatchNorm_1/Switch_2"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](batch_normalization_21/beta)]]
	 [[Node: strided_slice_53/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3459_strided_slice_53", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by wenlihaoyu** [comment]
检查tensorflow版本，版本太新可能会有一些问题
