### ISSUE TITLE
重新训练模型报错RuntimeError: Error(s) in loading state_dict for CRNN

### ISSUE THREAD

**Issue by Onebing** [chineseocr/chineseocr#324]
Traceback (most recent call last):
  File "D:/work/workspace/PycharmProjects/chineseocr-master/app.py", line 14, in <module>
    import model
  File "D:\work\workspace\PycharmProjects\chineseocr-master\model.py", line 9, in <module>
    from crnn.crnn_torch import crnnOcr as crnnOcr ##torch版本ocr
  File "D:\work\workspace\PycharmProjects\chineseocr-master\crnn\crnn_torch.py", line 48, in <module>
    model,converter = crnnSource()
  File "D:\work\workspace\PycharmProjects\chineseocr-master\crnn\crnn_torch.py", line 43, in crnnSource
    model.load_state_dict(modelWeights)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CRNN:
	size mismatch for rnn.1.embedding.weight: copying a param with shape torch.Size([5592, 512]) from checkpoint, the shape in current model is torch.Size([5530, 512]).
	size mismatch for rnn.1.embedding.bias: copying a param with shape torch.Size([5592]) from checkpoint, the shape in current model is torch.Size([5530]).

我是加载ocr-lstm.pth模型文件进行训练，得到modellstm.pth模型文件之后报错，请问这个问题这么解决。

**Comment by Onebing** [comment]
暂时找到解决方案了，alphabets让我改了，这个我该回去再训练试试。

**Comment by wenlihaoyu** [comment]
修改crnn/keys.py alphabetChinese 为你训练训练的字符集

**Comment by Onebing** [comment]
> 修改crnn / keys.py alphabetChinese为你训练训练的字符集

昨天修改了一下，问题解决了，谢谢您的回复

**Comment by Uncle-Justice** [comment]
我遇到的问题是，我明明输入的训练数据全是阿拉伯数字，却显示 torch.Size([]) 是63，请问这个是什么原因呢？

**Comment by coreychen** [comment]
> 我遇到的问题是，我明明输入的训练数据全是阿拉伯数字，却显示 torch.Size([]) 是63，请问这个是什么原因呢？

请问下，你训练的阿拉伯数组模型成功了吗，训练数据是怎么弄的，可否分享下？

**Comment by zfs1993** [comment]
请问您的训练文件是什么样子的，现在只能找到一个叫train-ocr.ipynb的文件，找不到train-ocr.py的文件了
