### ISSUE TITLE
服务启动报错

### ISSUE THREAD

**Issue by NeoWang9999** [chineseocr/chineseocr#336]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/neowang/mywork/ChineseOCR/chineseocr/app.py", line 4, in <module>
    import model
  File "/Users/neowang/mywork/ChineseOCR/chineseocr/model.py", line 30, in <module>
    from text import keras_detect as detect
  File "/Users/neowang/mywork/ChineseOCR/chineseocr/text/keras_detect.py", line 26, in <module>
    box_score = box_layer([*textModel.output,image_shape,input_shape],anchors, num_classes)
  File "/Users/neowang/mywork/ChineseOCR/chineseocr/text/keras_yolo3.py", line 365, in box_layer
    boxes  = concatenate(boxes, axis=0)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py", line 687, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 561, in __call__
    base_layer_utils.create_keras_history(inputs)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 200, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  [Previous line repeated 2 more times]
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 244, in _create_keras_history_helper
    constants[i] = backend.function([], op_input)([])
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/Users/neowang/mywork/ChineseOCR/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_368' with dtype float and shape [2]
	 [[{{node Placeholder_368}}]]

**Comment by foreseez** [comment]
这个问题  我遇到过，是你的TensorFlow 版本不对 你重新安下试试

**Comment by wting861006** [comment]
@zyjcs 你的tensorflow版本是多少

**Comment by yuanshengyu** [comment]
> 
> 
> @zyjcs 你的tensorflow版本是多少

遇到同样的问题，解决了吗？

**Comment by fatherworld** [comment]
同样遇到了这个问题 请问tensorflow的版本多少呢

**Comment by fatherworld** [comment]
> @zyjcs 你的tensorflow版本是多少

环境配置，支持linux\macOs

conda create -n chineseocr python=3.6 pip scipy numpy jupyter ipython ##运用conda 创建python环境
source activate chineseocr
git submodule init && git submodule update
pip install easydict opencv-contrib-python==4.0.0.21 Cython h5py lmdb mahotas pandas requests bs4 matplotlib lxml -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install -U pillow -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install keras==2.1.5 tensorflow==1.8 tensorflow-gpu==1.8
pip install web.py==0.40.dev0 redis conda install pytorch torchvision -c pytorch
pip install torch torchvision
