### ISSUE TITLE
crnn训练中文模型问题

### ISSUE THREAD

**Issue by xiaohuang1227** [chineseocr/chineseocr#338]
root@ecs-d8f1:/home/data/chineseocr# python train-ocr.py 
epoch:0/10
Traceback (most recent call last):
  File "train-ocr.py", line 180, in <module>
    cpu_images, cpu_texts = train_iter.next()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by ChenShaomin** [comment]
我也遇到这个问题了，请问找到解决方法了吗，谢谢

**Comment by Uncle-Justice** [comment]
i got the same problem

**Comment by huilinghap** [comment]
> root@ecs-d8f1:/home/data/chineseocr# python train-ocr.py
> epoch:0/10
> Traceback (most recent call last):
> File "train-ocr.py", line 180, in
> cpu_images, cpu_texts = train_iter.next()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> TypeError: function takes exactly 5 arguments (1 given)

@xiaohuang1227 您好~可以分享一下train-ocr.py文件吗？我在master分之下，没有找见该文件~多谢~

**Comment by zfs1993** [comment]
> root@ecs-d8f1:/home/data/chineseocr# python train-ocr.py
> epoch:0/10
> Traceback (most recent call last):
> File "train-ocr.py", line 180, in 
> cpu_images, cpu_texts = train_iter.next()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> TypeError: function takes exactly 5 arguments (1 given)

train-ocr.py请问这个文件还有吗？现在不知道为啥没了，不知道怎么训练了

**Comment by blair2020** [comment]
一模一样的错误，请问楼主解决了吗，我觉得可能是lmdb，我就改了这个就报这个错误

**Comment by blair2020** [comment]
我解决了，线程数改为0
