### ISSUE TITLE
in centos6.5 runing, find a error? anyone can tell me how to do? thanks 

### ISSUE THREAD

**Issue by baimin1** [chineseocr/chineseocr#374]
99 conv    128  1 x 1 / 1    76 x  76 x 384   ->    76 x  76 x 128  0.568 BFLOPs
  100 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  101 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
  102 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  103 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
  104 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  105 conv     21  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x  21  0.062 BFLOPs
  106 yolo
Loading weights from /home/ai/chineseocr/models/text.weights...Done!
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/chineseocr/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 213, in <module>
    app = web.application(urls, globals())
  File "/home/ai/anaconda3/envs/chineseocr/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/home/ai/anaconda3/envs/chineseocr/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/home/ai/anaconda3/envs/chineseocr/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration

**Comment by baimin1** [comment]
I got it by doing:

 ##  /home/ai/anaconda3/envs/chineseocr/lib/python3.7/site-packages/web//utils.py

  def take(seq, n):
        for i in range(n):
            #yield next(seq)
            ##modify  as following
            try:
                yield next(seq)
            except StopIteration:
                return

**Comment by baimin1** [comment]
I did it by,
1. Adjust a file from webpy inside your site-packages: web/utils.py
    def take(seq, n):
        for i in range(n):
            #yield next(seq)
            ##modified as following
            try:
                yield next(seq)
            except StopIteration:
                return


2.
Adjust a file from webpy inside your site-packages: web/httpserver.py
        self.start_response = start_response
        self.directory = os.getcwd() ## add

**Comment by kernelforce** [comment]
> I did it by,
> 
> 1. Adjust a file from webpy inside your site-packages: web/utils.py
>    def take(seq, n):
>    for i in range(n):
>    #yield next(seq)
>    ##modified as following
>    try:
>    yield next(seq)
>    except StopIteration:
>    return
> 
> Adjust a file from webpy inside your site-packages: web/httpserver.py
> self.start_response = start_response
> self.directory = os.getcwd() ## add

Thank you for your solution, which also solve the same problem on Win10
