### ISSUE TITLE
环境配置完运行app.py 8080 错误

### ISSUE THREAD

**Issue by fangpochen** [chineseocr/chineseocr#378]
(chineseocr) root@10-35-19-113 14:43:40 /tmp/chineseocr-app# python app.py 8080
Using TensorFlow backend.
WARNING:tensorflow:From /root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py:1456: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    from text.keras_detect import  text_detect
  File "/tmp/chineseocr-app/text/keras_detect.py", line 20, in <module>
    textModel.load_weights(kerasTextModel)
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 1101, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 148115456, sblock->base_addr = 0, stored_eof = 246891992)

**Comment by fangpochen** [comment]
h5py 文件没有吗。这是什么问题

**Comment by jun214384468** [comment]
你可以换一个端口号试一下

**Comment by lfp90** [comment]
咱们两个问题一样，请问您解决了吗

**Comment by jun214384468** [comment]
> 咱们两个问题一样，请问您解决了吗

我的解决了，我把端口号换成7070了，你可以随便换一个试试

**Comment by FeverKing** [comment]
还是这个报错,换成7070
