### ISSUE TITLE
ypeError: rotate() got an unexpected keyword argument 'center'

### ISSUE THREAD

**Issue by sxk000** [chineseocr/chineseocr#386]
为什么会出现这种错误？有人遇到过吗？该如何解决呢？
172.16.24.42:49234 - - [22/Oct/2019 10:40:30] "HTTP/1.1 GET /ocr" - 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 257, in process
    return self.handle()
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/home/wonders/kevin/wonders/2019/10_21_ocr/1_chineseocr/app.py", line 170, in POST
    rightAdjustAlph=0.01,##对检测的文本行进行向右延伸
  File "/home/wonders/kevin/wonders/2019/10_21_ocr/1_chineseocr/main.py", line 98, in model
    res                = self.ocr_batch(img,boxes,leftAdjustAlph,rightAdjustAlph)
  File "/home/wonders/kevin/wonders/2019/10_21_ocr/1_chineseocr/main.py", line 76, in ocr_batch
    partImg,box = rotate_cut_img(im,box,leftAdjustAlph,rightAdjustAlph)
  File "/home/wonders/kevin/wonders/2019/10_21_ocr/1_chineseocr/apphelper/image.py", line 199, in rotate_cut_img
    tmpImg = im.rotate(degree_,center=(cx,cy)).crop(box)
TypeError: rotate() got an unexpected keyword argument 'center'

172.16.24.42:49234 - - [22/Oct/2019 10:40:42] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

为什么会出现这种错误？有人遇到过吗？该如何解决呢？

**Comment by wenlihaoyu** [comment]
pillow包版本不正确，升级到最新版本

**Comment by sxk000** [comment]
@wenlihaoyu 的确是pillow版本不正确的问题，我升级到最新版本后，问题解决了，非常感谢您！
