### ISSUE TITLE
app.py错误

### ISSUE THREAD

**Issue by huillll** [chineseocr/chineseocr#391]
Using TensorFlow backend.
2019-11-03 09:56:06.046798: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-03 09:56:06.070035: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-11-03 09:56:06.070339: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3f087b0 executing computations on platform Host. Devices:
2019-11-03 09:56:06.070367: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "app.py", line 54, in <module>
    from text.keras_detect import  text_detect
  File "/home/luhui/chineseocr/text/keras_detect.py", line 24
    box_score = box_layer([*textModel.output,image_shape,input_shape],anchors, num_classes)
                           ^
SyntaxError: invalid syntax

**Comment by huillll** [comment]
python 2.7

**Comment by huillll** [comment]
python3 tools/pytorch_to_keras.py  -weights_path models/ocr-dense.pth -output_path models/ocr-dense-keras.h5
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-11-04 10:34:56.130559: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-04 10:34:56.133757: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-11-04 10:34:56.134024: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5f66eb0 executing computations on platform Host. Devices:
2019-11-04 10:34:56.134068: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>

**Comment by wenlihaoyu** [comment]
不支持python2.7
