### ISSUE TITLE
UnboundLocalError 

### ISSUE THREAD

**Issue by tanzikun** [chineseocr/chineseocr#394]
刚搭好docker 上传图片报这个错，大神帮忙看下
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/root/anaconda3/lib/python3.6/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/root/anaconda3/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/root/anaconda3/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/chineseocr/app.py", line 206, in POST
    return json.dumps({'res':res,'timeTake':round(timeTake,4)},ensure_ascii=False)
UnboundLocalError: local variable 'res' referenced before assignment

**Comment by RayJueZhu** [comment]
我也是这个问题请问解决了吗？？

**Comment by RayJueZhu** [comment]
已解决！版本问题,pip install opencv-python-4.1.1.26
