### ISSUE TITLE
求助：ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by huangyunjin** [chineseocr/chineseocr#403]
![1575520185639](https://user-images.githubusercontent.com/11924152/70204300-f994de80-175a-11ea-9079-5e5749fd168a.jpg)

Original exception was:
Traceback (most recent call last):
  File "app2.py", line 15, in <module>
    from ocr import do_model, crnn
  File "/qhapp/appsystems/apps/chineseocr-app/ocr.py", line 66, in <module>
    from crnn.network_torch import CRNN
  File "/qhapp/appsystems/apps/chineseocr-app/crnn/network_torch.py", line 9, in <module>
    import torch.nn as nn
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

请问这种情况是怎么回事啊？非常感谢

**Comment by huangyunjin** [comment]
求助求助

**Comment by wenlihaoyu** [comment]
你应该修改过代码吧，同时使用TF和torch，需要先导入torch，如果先导入TF，就会报错。

**Comment by DaoYB033** [comment]
原因：
导入顺序引起了冲突
终极解决方法：
在app.py的最前面加上一行：import torch
