### ISSUE TITLE
InvalidArgumentError: placeholder tensor 'Placeholder_395' with dtype float and shape [2]

### ISSUE THREAD

**Issue by clnFind** [chineseocr/chineseocr#440]
* 基于GPU环境运行程序时，出现以下错误；tensorflow版本用的1.15.0
* 想请教下楼主，以下问题怎么解决？

```
  File "/content/drive/My Drive/idcardOCR/model.py", line 21, in <module>
    from text import keras_detect as detect
  File "/content/drive/My Drive/idcardOCR/text/keras_detect.py", line 26, in <module>
    box_score = box_layer([*textModel.output,image_shape,input_shape],anchors, num_classes)
  File "/content/drive/My Drive/idcardOCR/text/keras_yolo3.py", line 365, in box_layer
    boxes  = concatenate(boxes, axis=0)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/merge.py", line 705, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 802, in __call__
    base_layer_utils.create_keras_history(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 184, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 229, in _create_keras_history_helper
    constants[i] = backend.function([], op_input)([])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_395' with dtype float and shape [2]
	 [[{{node Placeholder_395}}]]
```

**Comment by wenlihaoyu** [comment]
高版本tf好像有这个问题，你可以降低tf的版本。近期会代码升级，支持cuda10及最新版本的支持。

**Comment by tianyazhe233** [comment]
> 高版本tf好像有这个问题，你可以降低tf的版本。近期会代码升级，支持cuda10及最新版本的支持。

[图片]我用的cpu跑的，tf1.14，也有类似的问题，我看有人是用python3.6版本，https://zlotus.github.io/2019/08/24/rbp3-chinese-text-dection/，是这个原因吗

**Comment by tianyazhe233** [comment]
> 高版本tf好像有这个问题，你可以降低tf的版本。近期会代码升级，支持cuda10及最新版本的支持。

我用的cpu跑的，tf1.14，在运行/text-train.ipynb的时候也有类似的问题，我看有人是用python3.6版本，https://zlotus.github.io/2019/08/24/rbp3-chinese-text-dection/，是这个原因吗

Traceback (most recent call last):
  File "aa.py", line 28, in <module>
    box_score = box_layer([*textModelTest.output,image_shape,input_shape],anchors, num_classes)
  File "/home/train/chineseocr-master-train/text/keras_yolo3.py", line 365, in box_layer
    boxes  = concatenate(boxes, axis=0)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/merge.py", line 687, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 561, in __call__
    base_layer_utils.create_keras_history(inputs)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 200, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 246, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 244, in _create_keras_history_helper
    constants[i] = backend.function([], op_input)([])
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/train/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_367' with dtype float and shape [2]
         [[{{node Placeholder_367}}]]
