### ISSUE TITLE
前端页面显示异常，点击浏览无反应 

### ISSUE THREAD

**Issue by xxllp** [chineseocr/chineseocr#46]
后台的log 
10.0.0.72:60398 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /ocr" - 200 OK
10.0.0.72:60399 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /static/js/jquery.js" - 304 Not Modified
10.0.0.72:60398 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /static/css/bootstrap.min.css" - 304 Not Modified
10.0.0.72:60400 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /static/js/jquery.form.js" - 304 Not Modified
10.0.0.72:60401 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /static/js/helps.js" - 304 Not Modified
10.0.0.72:60402 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /static/img/loading.gif" - 304 Not Modified
10.0.0.72:60420 - - [14/Sep/2018 15:25:32] "HTTP/1.1 GET /ocr" - 200 OK
10.0.0.72:60420 - - [14/Sep/2018 15:25:33] "HTTP/1.1 GET /css/zzsc.css" - 404 Not Found
10.0.0.72:60424 - - [14/Sep/2018 15:25:33] "HTTP/1.1 GET /favicon.ico" - 404 Not Found

**Comment by xxllp** [comment]
难道是路径的问题？

**Comment by xxllp** [comment]
TypeError('WSGI response header value 469 is not of type str.',)
Traceback (most recent call last):
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 1982, in respond
    for chunk in response:
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/httpserver.py", line 267, in __iter__
    self.start_response(self.status, self.headers)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/httpserver.py", line 320, in xstart_response
    out = start_response(status, response_headers, *args)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 2029, in start_response
    "WSGI response header value %r is not of type str." % v)
TypeError: WSGI response header value 469 is not of type str.

**Comment by wenlihaoyu** [comment]
"10.0.0.72:60398 - - [14/Sep/2018 15:25:17] "HTTP/1.1 GET /ocr" - 200 OK"，看你日志，是正常的。WSGI异常可以忽略。

**Comment by xxllp** [comment]
但是我前端没反应，这个怎么说呢

**Comment by guowenjia** [comment]
@xxllp 你的问题可能是与访问ip有问题。你设置成你本机内网ip比如http://192.168.1.41:8080/ocr  试一下。

**Comment by ljg-lixufeng** [comment]
> @xxllp 你的问题可能是与访问ip有问题。你设置成你本机内网ip比如http://192.168.1.41:8080/ocr 试一下。

你好，我的也出现这个问题，请问该怎么设置本机内网ip呢

**Comment by 489397771** [comment]
> > @xxllp你的问题可能是与访问IP有问题。你设置成你本机内网IP比如http://192.168.1.41:8080/ocr试一下。
> 
> 你好，我的也出现这个问题，请问该怎么设置本机内网IP呢

你好，你的问题解决了么？我今天也出现这个问题了

**Comment by ljg-lixufeng** [comment]
你好，我没有解决，改了下代码，没有用作者展示的那一部分

在 2019-01-07 11:13:03，"Helen" <notifications@github.com> 写道：


@xxllp你的问题可能是与访问IP有问题。你设置成你本机内网IP比如http://192.168.1.41:8080/ocr试一下。

你好，我的也出现这个问题，请问该怎么设置本机内网IP呢

你好，你的问题解决了么？我今天也出现这个问题了

**Comment by 489397771** [comment]
> 你好，我没有解决，改了下代码，没有用作者展示的那一部分 在 2019-01-07 11:13:03，"Helen" <notifications@github.com> 写道： @xxllp你的问题可能是与访问IP有问题。你设置成你本机内网IP比如[http://192.168.1.41:8080/ocr试一下。](http://192.168.1.41:8080/ocr%E8%AF%95%E4%B8%80%E4%B8%8B%E3%80%82) 你好，我的也出现这个问题，请问该怎么设置本机内网IP呢 你好，你的问题解决了么？我今天也出现这个问题了
-----------------------------------------------------------------------------------------------------------------
再打扰你一下，之前的问题解决的，但是运行到这boxes_table[int(box[0])].append(index)报错了，因为box[0]是个长度为4的list无法转换成int格式，你遇到过么？是怎么处理的，或者麻烦你帮我解释一下这段代码的作用是什么？

**Comment by lwt001no1** [comment]
我之前是这个问题，后来把我用的python3.7改成了3.6就好了
