### ISSUE TITLE
作者您好！当我两个客户端同时发起请求时，也就是任务并行时，会出现如下错误。是否正常呢？

### ISSUE THREAD

**Issue by BlackCodeMan** [chineseocr/chineseocr#51]
Traceback (most recent call last):
  File "/Users/karmanzeng/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/Users/karmanzeng/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/karmanzeng/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/Users/karmanzeng/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/app.py", line 71, in POST
    leftAdjust=True, rightAdjust=True, alph=0.1)
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/model.py", line 214, in model
    text_recs,tmp = text_detect(**config)
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/model.py", line 47, in text_detect
    MIN_NUM_PROPOSALS)
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/detector/detectors.py", line 70, in detect
    text_lines=self.text_proposal_connector.get_text_lines(text_proposals, scores, size)##合并文本行
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/detector/text_proposal_connector.py", line 29, in get_text_lines
    tp_groups=self.group_text_proposals(text_proposals, scores, im_size)##find the text line
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/detector/text_proposal_connector.py", line 12, in group_text_proposals
    graph=self.graph_builder.build_graph(text_proposals, scores, im_size)
  File "/Users/karmanzeng/PycharmProjects/chineseocr-master/detector/text_proposal_graph_builder.py", line 88, in build_graph
    boxes_table[int(box[0])].append(index)
IndexError: list index out of range

**Comment by wenlihaoyu** [comment]
你要作并发请求，应该用队列去控制，本项目只是一个简单的demo

**Comment by zhuguangqiang** [comment]
并发的时候，上面2个错我都出现过，这个代码应该是哪里有问题，可能有全局共享变量之类的导致问题

**Comment by BlackCodeMan** [comment]
> 并发的时候，上面2个错我都出现过，这个代码应该是哪里有问题，可能有全局共享变量之类的导致问题



> 并发的时候，上面2个错我都出现过，这个代码应该是哪里有问题，可能有全局共享变量之类的导致问题

请问后来找到问题所在了吗？

**Comment by zhuguangqiang** [comment]
是opencv.dnn框架的问题，它的text_detect模型的对象只能支持单张图片检测，如果同时检测两张图片就会崩溃，通过一次性实例化多个模型对象放入资源池，轮流取用空闲的模型来检测，可以缓解这个问题。不过我最终是把darknet模型转换为keras模型来彻底解决这个问题了
