### ISSUE TITLE
win10环境  ipython app.py 8080    这里为什么是ipython  这步无法启动

### ISSUE THREAD

**Issue by QQ2737499951** [chineseocr/chineseocr#56]
cd chineseocr## 进入chineseocr目录
ipython app.py 8080 ##8080端口号，可以设置任意端口

---------------------

 这里为什么是ipython  这步无法启动

**Comment by QQ2737499951** [comment]
G:\Tensorflow\yolo v3\chineseocr-master>python app.py 8080
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    import model
  File "G:\Tensorflow\yolo v3\chineseocr-master\model.py", line 3, in <module>
    from detector.detectors import TextDetector
  File "G:\Tensorflow\yolo v3\chineseocr-master\detector\detectors.py", line 5, in <module>
    from detector.utils.cython_nms import nms as cython_nms
  File "G:\Tensorflow\yolo v3\chineseocr-master\detector\utils\__init__.py", line 1, in <module>
    from . import cython_nms
ImportError: cannot import name 'cython_nms'

**Comment by QQ2737499951** [comment]
把 在其他项目生成的 bbox.cp36-win_amd64.pyd、cython_nms.cp36-win_amd64.pyd、gpu_nms.cp36-win_amd64.pyd这3个文件 复制到 G:\Tensorflow\yolo v3\chineseocr-master\detector\utils\目录后，再次运行python app.py 8080

G:\Tensorflow\yolo v3\chineseocr-master>python app.py 8080
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    import model
  File "G:\Tensorflow\yolo v3\chineseocr-master\model.py", line 5, in <module>
    import darknet_detect
  File "G:\Tensorflow\yolo v3\chineseocr-master\darknet_detect.py", line 55, in <module>
    net = dn.load_net(yoloCfg.encode('utf-8'), yoloWeights.encode('utf-8'), 0)
AttributeError: module 'darknet' has no attribute 'load_net'

**Comment by QQ2737499951** [comment]
win10+python3.66+vs2017+cuda9.2  我的环境是

**Comment by wenlihaoyu** [comment]
ipython/python均可以，或者你可以将model.py 第5行注释掉，看能不能启动
```
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from detector.detectors import TextDetector
from detector.other import get_boxes
#import darknet_detect
import opencv_dnn_detect ##opencv dnn model for darknet
import numpy as np
from PIL import Image
import numpy as np
import time
import cv2
from glob import glob
from crnn.crnn import crnnOcr as crnnOcr 
```

**Comment by beimingmaster** [comment]
是不是python版本的问题？
Python Version：3.5.2
CUDA Version: 8.0.61
CUDNN Version: 6.0.21
Linux Version: Ubuntu 16.04.3 LTS

**Comment by beimingmaster** [comment]
原因搞清楚了，这步骤没执行就会报cython_nms错误：
pushd detector/utils && sh make-for-cpu.sh && popd

**Comment by beimingmaster** [comment]
最好在linux上测试，windows上的环境太难搞了。

**Comment by beimingmaster** [comment]
> pushd detector/utils && sh make-for-cpu.sh && popd 这一步 在win 环境怎样操作？

windows环境太麻烦了，估计你要先装cygwin，否则很多命令都没有。

**Comment by QQ2737499951** [comment]
我先装一下 cygwin

**Comment by QQ2737499951** [comment]
gpu 环境下安装 ，，setup.sh这个文件最后一行错了


##环境配置，支持linux\macOs
conda create -n chineseocr python=3.6 pip scipy numpy jupyter ipython ##运用conda 创建python环境
source activate chineseocr
git submodule init && git submodule update
pip install easydict opencv-contrib-python Cython  -i https://pypi.tuna.tsinghua.edu.cn/simple/ ##选择国内源，速度更快
pip install -U pillow -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install  h5py lmdb mahotas pandas,requests -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install web.py==0.40.dev0
conda install pytorch=0.2.0 cuda80  torchvision -c soumith
pushd detector/utils && sh make-for-cpu.sh && popd

最后一行应该错了。 G:\Tensorflow\yolo v3\chineseocr-master\detector\utils\make.sh  应该是这样的

**Comment by QQ2737499951** [comment]
gpu 环境下安装 ，G:\Tensorflow\yolo v3\chineseocr-master\detector\utils\make.sh

cython bbox.pyx
cython cython_nms.pyx
cython gpu_nms.pyx
python setup.py build_ext --inplace
mv utils/* ./
rm -rf build
rm -rf utils

------------
linux下直接就输入 cython bbox.pyx  就可以了吗？
win环境 

G:\>cd G:\Tensorflow\yolo v3\chineseocr-master\detector\utils\

G:\Tensorflow\yolo v3\chineseocr-master\detector\utils>cython bbox.pyx
'cython' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

G:\Tensorflow\yolo v3\chineseocr-master\detector\utils>

============
cython已经安装完毕，也没问题，测试过生成过pyd文件
C:\Users\WWWW>pip install cython
Requirement already satisfied: cython in d:\program files\python366\lib\site-packages (0.28.5)

C:\Users\WWWW>

**Comment by wenlihaoyu** [comment]
@QQ2737499951 在windows上面装一个docker容器，要用GPU，就装nvidia-docker，也不用这样折腾。

**Comment by QQ2737499951** [comment]
方便加一下qq吗？谢谢或有qq群吗

**Comment by wenlihaoyu** [comment]
@QQ2737499951 在windows编译应该要修改 setup.py文件的内容，或者不用这一块，可以用纯python代码实现nms算法，在detectos.py 文件中
```
#coding:utf-8
from detector.other import  normalize
import numpy as np
import numpy as np
#from detector.utils.cython_nms import nms as cython_nms
#try:
#    from detector.utils.gpu_nms import gpu_nms
#except:
#    gpu_nms =cython_nms

def nms(dets, thresh):
    if dets.shape[0] == 0:
        return []
    try:
           return gpu_nms(dets, thresh, device_id=0)
    except:
            return cython_nms(dets, thresh)

```
将nms 函数替换为如下内容：
```
def nms(boxes, threshold, method='Union'):
    if boxes.size==0:
        return np.empty((0,3))
    x1 = boxes[:,0]
    y1 = boxes[:,1]
    x2 = boxes[:,2]
    y2 = boxes[:,3]
    s = boxes[:,4]
    area = (x2-x1+1) * (y2-y1+1)
    I = np.argsort(s)
    pick = np.zeros_like(s, dtype=np.int16)
    counter = 0
    while I.size>0:
        i = I[-1]
        pick[counter] = i
        counter += 1
        idx = I[0:-1]
        xx1 = np.maximum(x1[i], x1[idx])
        yy1 = np.maximum(y1[i], y1[idx])
        xx2 = np.minimum(x2[i], x2[idx])
        yy2 = np.minimum(y2[i], y2[idx])
        w = np.maximum(0.0, xx2-xx1+1)
        h = np.maximum(0.0, yy2-yy1+1)
        inter = w * h
        if method is 'Min':
            o = inter / np.minimum(area[i], area[idx])
        else:
            o = inter / (area[i] + area[idx] - inter)
        I = I[np.where(o<=threshold)]
    pick = pick[0:counter]
    return pick
```

**Comment by wenlihaoyu** [comment]
还是搞不定的话，可以加我微信号:lywen52

**Comment by yunxinan** [comment]
这个问题我的解决方法是升级了linux的gcc ，一般不同的系统升级方式不一样。红帽是sudo yum 而ubuntu是通过sudo apt-get实现。然后复制最后一段代码单独执行一下问题就解决了。这个问题我折腾的很久发现的解决方案。windows也可以通过这种类方案。 同时非常感谢作者修改并发问题，文件为repo

**Comment by QQ2737499951** [comment]
> 这个问题我的解决方法是升级了linux的gcc ，一般不同的系统升级方式不一样。红帽是sudo yum 而ubuntu是通过sudo apt-get实现。然后复制最后一段代码单独执行一下问题就解决了。这个问题我折腾的很久发现的解决方案。windows也可以通过这种类方案。 同时非常感谢作者修改并发问题，文件为repo

您有qq吗？加qq学习一下谢谢！QQ2737499951

**Comment by amberblade** [comment]
gpu版本的nms可以参考我的修改[https://github.com/amberblade/gpu_nms_windows](https://github.com/amberblade/gpu_nms_windows)，或者直接是用python版的nms

**Comment by upwon** [comment]
请问解决了Windows下的cannot import name 'cython_nms'这个问题了吗 还是非要去Linux下才可以 @QQ2737499951

**Comment by yunxinan** [comment]
这是一个gcc升级问题，你要用windows下的shell命令去升级和重新更新Cpython编译python代码
________________________________
发件人: upwon <notifications@github.com>
发送时间: 2018年11月28日 13:03
收件人: chineseocr/chineseocr
抄送: An Jun-gang; Comment
主题: Re: [chineseocr/chineseocr] win10环境 ipython app.py 8080 这里为什么是ipython 这步无法启动 (#56)


请问解决了Windows下的cannot import name 'cython_nms'这个问题了吗 还是非要去Linux下才可以 @QQ2737499951<https://github.com/QQ2737499951>

―
