### ISSUE TITLE
text_detect() got an unexpected keyword argument 'textmodel'

### ISSUE THREAD

**Issue by bitdata** [chineseocr/chineseocr#65]
Traceback (most recent call last):
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/root/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/usr/local/src/github/chineseocr/chineseocr/app.py", line 59, in POST
    leftAdjust=True,rightAdjust=True,alph=0.1)
  File "/usr/local/src/github/chineseocr/chineseocr/model.py", line 282, in model
    text_recs,tmp = text_detect(**config)
TypeError: text_detect() got an unexpected keyword argument 'textmodel'

看了一下源码，应该是改版造成的文件之间的不一致。在app.py中去除textmodel = 'opencv_dnn_detect'及前面的逗号即可。而在config.py中修改opencvFlag来设置是否使用OpenCV。

**Comment by NormalAppler** [comment]
我再运行的时候也报了此问题，去掉后能成功运行

**Comment by wenlihaoyu** [comment]
app.py文件忘记提交了
