### ISSUE TITLE
cv2.dnn.readNetFromDarknet error

### ISSUE THREAD

**Issue by universewill** [chineseocr/chineseocr#70]
How to solve this?:

```
OpenCV(3.4.1) Error: Parsing error (Unknown layer type: shortcut) in ReadDarknetFromCfgFile, file /io/opencv/modules/dnn/src/darknet/darknet_io.cpp, line 503
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    import model
  File "/home/universe/jupyter/gxl/project/ocr/chineseocr/model.py", line 7, in <module>
    from opencv_dnn_detect import angle_detect##文字方向检测
  File "/home/universe/jupyter/gxl/project/ocr/chineseocr/opencv_dnn_detect.py", line 7, in <module>
    textNet = cv2.dnn.readNetFromDarknet(yoloCfg,yoloWeights)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:503: error: (-212) Unknown layer type: shortcut in function ReadDarknetFromCfgFile
```

**Comment by wenlihaoyu** [comment]
opencv>=3.4.2

**Comment by xiaosi2017** [comment]
cv2.dnn.readNetFromDarknet
cv2.dnn.readNetFromTensorflow
cv2.dnn.blobFromImage
请问opencv_dnn_detect.py 里面的这三个dnn函数可以用tf或者keras改写吗，想用gpu加速
