### ISSUE TITLE
自己训练的crnn模型文件，放到models目录下报错

### ISSUE THREAD

**Issue by beimingmaster** [chineseocr/chineseocr#78]
Loading weights from /ml/github/chineseocr/models/text.weights...Done!
While copying the parameter named rnn.1.embedding.weight, whose dimensions in the model are torch.Size([5530, 512]) and whose dimensions in the checkpoint are torch.Size([6736, 512]), ...
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    import model
  File "/ml/github/chineseocr/model.py", line 13, in <module>
    from crnn.crnn import crnnOcr as crnnOcr 
  File "/ml/github/chineseocr/crnn/crnn.py", line 37, in <module>
    model,converter = crnnSource()
  File "/ml/github/chineseocr/crnn/crnn.py", line 31, in crnnSource
    model.load_state_dict(new_state_dict)
  File "/home/master/.virtualenvs/dl4cv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: inconsistent tensor size, expected tensor [5530 x 512] and src [6736 x 512] to have the same number of elements, but got 2831360 and 3448832 elements respectively at /pytorch/torch/lib/TH/generic/THTensorCopy.c:86

说模型参数不一致，这个要如何调整？
text.weights如何重新生成？

**Comment by Aurora11111** [comment]
[5530 x 512] and src [6736 x 512]调整alphabet

**Comment by beimingmaster** [comment]
> [5530 x 512] and src [6736 x 512]调整alphabet

谢谢，可以了！

不过自己训练的模型比作者提供的模型识别能力差了好多。

**Comment by mocorr** [comment]
@beimingmaster 请问您能不能把您crnn训练的代码发一下呢？非常感谢。我想基于作者的model进行训练，但没有训练代码有些无从下手。希望能得到帮助

**Comment by Aurora11111** [comment]
@mocorr reference:https://github.com/Aurora11111/crnn-train-pytorch

**Comment by beimingmaster** [comment]
> @beimingmaster 请问您能不能把您crnn训练的代码发一下呢？非常感谢。我想基于作者的model进行训练，但没有训练代码有些无从下手。希望能得到帮助

https://github.com/Sierkinhane/crnn_chinese_characters_rec

我是按照这个开源项目来训练的。

**Comment by mocorr** [comment]
@beimingmaster 好的谢谢~

**Comment by OKhyc** [comment]
是不是说 比如我有自己的图片文件，按照这个开源的软件训练完成，生成的东西直接放到models文件夹里面就能运行了。需不需要将models文件夹里面的作者的文件删除？

**Comment by OKhyc** [comment]
我按照这个训练项目 训练数据  但是python2.7 一直报没有lmdb模块  ，但是我的python3.6.5是可以正常导入lmdb不知道是什么原因
