### ISSUE TITLE
作者您好,训练crnn的代码会公布么?

### ISSUE THREAD

**Issue by Cony07f5** [chineseocr/chineseocr#9]

**Comment by wenlihaoyu** [comment]
crnn训练可参考  https://github.com/meijieru/crnn.pytorch.git

**Comment by xray1111** [comment]
@wenlihaoyu https://github.com/meijieru/crnn.pytorch.git这个项目下训练的model可以直接拿到本项目使用吗？

**Comment by wenlihaoyu** [comment]
@xray1111 可以

**Comment by Cony07f5** [comment]
谢谢作者

**Comment by Aurora11111** [comment]
我把crnn.pth放本项目使用报错:
Loading weights from /home/rice/PycharmProjects/chineseocr/models/text.weights...Done!
Traceback (most recent call last):
  File "/home/rice/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 514, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rice/PycharmProjects/chineseocr/chineseocr_local.py", line 9, in <module>
    import model
  File "/home/rice/PycharmProjects/chineseocr/model.py", line 12, in <module>
    from crnn.crnn import crnnOcr as crnnOcr
  File "/home/rice/PycharmProjects/chineseocr/crnn/crnn.py", line 38, in <module>
    model,converter = crnnSource()
  File "/home/rice/PycharmProjects/chineseocr/crnn/crnn.py", line 32, in crnnSource
    model.load_state_dict(new_state_dict)
  File "/home/rice/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named rnn.1.embedding.weight, whose dimensions in the model are torch.Size([5530, 512]) and whose dimensions in the checkpoint are torch.Size([37, 512]).

**Comment by wenlihaoyu** [comment]
修改keys.py  alphabet='0123456789abcdefghijklmnopqrstuvwxyz'，crnn.pytorch 只能识别英文

**Comment by SolinTao** [comment]
@wenlihaoyu 你好，我试了把ocr.pth放在crnn.pytorch不能运行，使用crnn.pth可以识别，我想在ocr.pth的基础上继续训练，应该怎么办呢？谢谢。CRNN中训练数据的格式是LMDB吗？

**Comment by wenlihaoyu** [comment]
需要修改crnn.pytorch 默认--alphabet ，用本项目中keys.py文件的alphabet替换。

**Comment by OKhyc** [comment]
我cpu环境，也能参照这个案例去训练吗

**Comment by SolinTao** [comment]
> 我cpu环境，也能参照这个案例去训练吗

可以的

**Comment by OKhyc** [comment]
我目前仅具备文字图片 以及图片的txt标注文件。      我想通过crnn.pytorch这个项目来训练，让本项目(chineseocr)能识别我的文字。   crnn.pytorch训练完成 ，得到的是一个pth文件吗。
那么我是否需要将此文件，放到chineseocr项目models里面么。  
我对于总体的流程并不是很理解。

**Comment by chenyanghe** [comment]
crnn.pytorch这个项目的模型文件（作者自带的）是一个打包类型，不是.pth二进制文件啊？是不是用到这边来得换读取方式？
